### ISSUE TITLE
no blood/gore fx on bullet impacts

### ISSUE THREAD

**Issue by Jimmy-Baby** [ampreeT/SourceCoop#55]
Hi,

Apologies if this has already been explained, but, why are there no blood/gore fx on NPC's when they are hit by bullets/crowbar/etc when playing with sourcecoop?

I have started writing a plugin to try to accomodate for this lacking feature, though, I am having issues with it so far. 

Thanks.

**Comment by Alienmario** [comment]
It's a prediction issue. You can test this by setting cl_predict 0. They might still get created on the server, just not sent to clients. If that's the case, a solution would be a matter of hooking a Temp ent and changing the clients.

**Comment by Jimmy-Baby** [comment]
setting cl_predict to 0 fixed all of the gore effects straight away! thanks for the reply. :)

unfortunately, for any clients of the server, all movement inputs are delayed by however much latency they have to the server. which makes sense of course, considering the console commands name.

I will look into your suggestion. thanks again 👍🏻

**Comment by Alienmario** [comment]
I also noticed you can't only see the fx from your own damage. When others shoot, it shows correctly.

**Comment by Jimmy-Baby** [comment]
Ah! Good observation; I didn't even think to check if this was the case. I assumed it was the same for all damage dealt, with all clients spawned in.

I hate to ask, I am used to figuring these things out on my own, but I am quite unfamiliar with sourcepawn, and sourcemod especially. I literally only started looking into SP two days ago. Luckily it's very very similar to C, which I've been using for a few years now.

What do you mean when you say 'hooking a temp ent and changing the clients'? Are you saying I should try to create an sdkhook whenever an entity is created, check if it is an FX entity by filtering by classname, and then somehow making sure they are replicated on the client that dealt the damage? (As it seems all other clients see the FX already).

Feel free to give an as simple an answer as you wish, you've done some great work on the mod already :)

**Comment by ampreeT** [comment]
Its been a while since I have done work on the mod and anything Source Engine related so apologies in advance if the information or potential solutions that I provide are incorrect.

To give some insight on SourceMod and SourcePawn, SourcePawn is actually very C-like with some C++ functionality such as MethodMaps mimicing structs and classes. SourceMod provides signature scans, vtable indexes and hardcoded offsets through the gamedata folder/files. You can dereference/read/write pointer objects using [LoadFromAddress](https://sm.alliedmods.net/new-api/sourcemod/LoadFromAddress) and [StoreToAddress](https://sm.alliedmods.net/new-api/sourcemod/StoreToAddress). and You will be commonly running your logic in SourcePawn through hooks already provided by SDKHooks or the other default hooks. If you wish to hook functions that you have offsets for inside your custom gamedata, you'll need to use a custom extension called [DHooks](https://forums.alliedmods.net/showpost.php?p=2588686&postcount=589).  You'll be able to hook virtual functions and detour functions with this extension.

As for potential solutions, you could hook the NPC's SDKHook_OnTakeDamage using the SourcePawn function [SDKHook](https://sm.alliedmods.net/new-api/sdkhooks/SDKHook) and check who the attacker is. If the attacker is a player using a hitscan weapon, you could try running a [traceray](https://sm.alliedmods.net/new-api/sdktools_trace/TR_TraceRayEx) that runs from the player's eye angles and getting the position of the result. From there, you can emit a particle effect (I do not remember how to but I'll leave this as a exercise for you) on that position.

I hope this was informative. If you need any more information or run into any problems, feel free to ask! We always need more contributors to complete the full vision the mod.

**Comment by Jimmy-Baby** [comment]
Thanks for the response, ampreeT.

I have done hooking stuff before in C++ in the kernel and in games and stuff. It all seems relatively the same.

Below there's a screenshot of my OnTakeDamage hook I have been testing with. As it stands it crashes the server when enabled, but only when the hook is hit. Also, I know the hook is working properly. It is the code within the hook function causing the crash.

I have a feeling the issue lies in the fact that I'm maybe using entity references/indexes incorrectly? I can't see what else is wrong.

https://imgur.com/a/xavAVMT

Once I get everything working I'll add some menu options in the pre-existing sourcecoop menu for this and make a pull rq. :)

**Comment by ampreeT** [comment]
Try looking at the debug/crash logs if you are able to get any. SourceMod will catch any SourcePawn errors thrown and will print them out into the console. From what I can see, you will need to close the handle that you received from TR_TraceRayEx(...). You also might need to precache the sound using [PrecacheSound](https://sm.alliedmods.net/new-api/halflife/PrecacheSound) if it isn't being executed somewhere else. Try also passing BloodParticle.GetEntIndex() as the first parameter of TeleportEntity(...) as our CBaseEntity methodmap is custom (It may be passing this as a invalid pointer address). You can alternatively use it as BloodParticle.Teleport(...) as our methodmap wraps most member functions.

**Comment by Balimbanana** [comment]
I am not sure if this has been updated or if it will be implemented at some point, but I do have a method as well hooking in to:
`AddTempEntHook("WeaponBullets", ReCreateImpact);`
Although you also need to hook OnTakeDamage for melee weapons, it might be better to do it all through OnTakeDamage, but this tempent hook gives exact bullet shoot from origin, and angles that it is heading in.

For the particle effect, you should use the property of the target: `m_bloodColor` to set the type of blood to emit, this also ensures that tanks and `npc_plantlight` don't emit blood at all as they have blood color -1.

**Comment by Alienmario** [comment]
It hasn't been fixed yet.
I'd recommend going the path of least resistance - there are too many effects to recreate manually.
Have you tried hooking EffectDispatch tempent? Also Black mesa has an extra tempent "BlackMesa Shot".

**Comment by Balimbanana** [comment]
I haven't tested EffectDispatch yet, the other tempents for BloodSpray don't seem to work. The TempEnt for "BlackMesa Shot" also never fires, Only "WeaponBullets" seems to be used (at least in co-op, not sure about multiplayer).

**Comment by Jimmy-Baby** [comment]
Hi again,

apologies for the nooby question - I am STILL inexperienced with sourcepawn and modding - but, how am I supposed to find the prototypes for functions such as "WeaponBullets" or any of the code involving them. Other than trying to RE them myself, of course.

I am trying to give this plugin another go.

Thanks.
