### ISSUE TITLE
Spawn additional monsters?

### ISSUE THREAD

**Issue by aitap** [ampreeT/SourceCoop#64]
Hi and thanks for your work on this plugin,

Do you think it could be feasible to spawn additional enemies proportionally to the number of players so that everyone would have targets to shoot? I realise this isn't as simple as "just copy and paste the monsters at runtime" (imagine having to fight 5 gonarches or to come up with a place for an extra set of Blast Pit tentacles); handling players joining and leaving in the middle of a map could be a major source of pain, too.

We've been playing with friends, and noticed that the increased damage from the monsters with scaled difficulty mostly results in us having to respawn a lot. When we lower the difficulty, the person going in the front ends up mowing down most of the monsters, not leaving much for the rest of us. Perhaps having more monsters output less damage could bring some balance to the situation?

If you think it's feasible and has a chance of getting accepted, I could try to find out how to hook enemies being created (is there a better way?) and start working on a patch. Although I haven't programmed Pawn before, I do have C and C++ experience.

**Comment by Alienmario** [comment]
It would be very difficult. You'd have to go through each map and figure out where it makes sense. You'd be altering the flow of the maps (so far, we've been trying to keep it close to the original). You'd have to account for scripted NPCs. Some NPCs might have outputs that trigger something on death, etc. Then there's an issue with performance loss per npc, since they are not very optimized for multiplayer, having many NPCs can lag the server.
If this were to be realized, there'd have to be a system which works with our map scripts, so it can duplicate pre-selected npcs.

Imo, the this would be best solved with maps custom made for multiplayer, though I haven't seen much development in this area.

**Comment by aitap** [comment]
> You'd have to go through each map and figure out where it makes
> sense. You'd be altering the flow of the maps (so far, we've been
> trying to keep it close to the original).

Thanks for the answer. Keeping the flow of the game is a worthy goal,
which is indeed incompatible with my idea.
