### ISSUE TITLE
FR: Black Mesa: Blue Shift Support

### ISSUE THREAD

**Issue by holgerschillack** [ampreeT/SourceCoop#70]
Hi,

thank you very much for the Coop Mode plugin for Black Mesa, I already spent couple of hours with my colleagues having fun in BM.

I recently discovered that there is another remake coming or already released in parts: Black Mesa: Blue Shift
Link to Mod DB: https://www.moddb.com/mods/black-mesa-blue-shift-remake/downloads/black-mesa-blue-shift-chapters-1-3

What would the expense be to also make that supported by your plugin - as BM:BS is a mod of BM itself.

Another question: Is there any source or documentation that you used to make this plugin? So I could maybe in the future try to implement something like that myself or help with a PR.

It's a new era of fun playing with friends through the whole HL universe :) We're using Sven-Coop, Synergy and SourceCoop for the complete experience so far.

**Comment by Alienmario** [comment]
Thank you for your interest.

Supporting mods like Blue Shift is definitely one of nice-to-haves, however these total conversions turn out are complicated to run in the "standalone server" setup, because they require manual interventions (installing, enabling, disabling) and that's for both client and server. You could probably run a blue-shift only server fairly easily, if that's the intention.

We might look into supporting it once it is completed. That is because any modifications we do to the maps can cease to work with each of the mod's updates.

If you're willing to learn a new (but simple) language, it can be quite rewarding:
Here are the docs: https://wiki.alliedmods.net/Category:SourceMod_Scripting
Additional resources once you know the basics: https://forums.alliedmods.net/showthread.php?t=321089

**Comment by Alienmario** [comment]
New thread for map requests: #80
