### ISSUE TITLE
Game Closing after certain triggers

### ISSUE THREAD

**Issue by Ituladan** [ampreeT/SourceCoop#82]
Hello! I've instaled the latest resources and mods yesterday. 
The server work fine, but, my game close after some triggers:
- If I die, my game close, server continue fine with my friend
- If I drown, my game close, server continue fine
- If my friend turn him flashlight on, my game close

That's it, all other features are fine, server seems OK, my friend's game doesn't close, just my game. I'm who runs de server.
Example os console message after death and game closing:

Client "Leo N." connected (26.175.73.181:27005).
Server waking up from hibernation
CreateInstance called on a point_template that has no templates: new_game_spawn
CSceneEntity gman_generic_scene unable to find actor named "!player"
Player "Leo N." joined team spectator
[SRCCOOP] (chat) Difficulty has changed to 2
[SRCCOOP] Co-op map bm_c1a1c has begun
SV_StartSound:  not precached (0)
Entity 977 (class 'npc_zombie_scientist') reported ENTITY_CHANGE_NONE but 'm_hEffectEntity' changed.
[SRCCOOP] (chat) Difficulty has changed to 0
Dropped Leo N. from server (Leo N. timed out)
Server is hibernating

**Comment by Alienmario** [comment]
Some people (especially on weaker machines) are known to crash when rendering the flashlight. There's not much we can do about it. You may disable it on the server by mp_flashlight 0.

By latest resources and mods you mean the beta version 1.1.x?

There will be a patch that fixes a crash when killed by other player. I don't know if it's related to your issue though. If you friend doesn't crash at all, it's likely an issue with your pc, as with the flashlight.

**Comment by Balimbanana** [comment]
You can also test out running Black Mesa on Vulkan by this:
https://github.com/doitsujin/dxvk/releases

You download the archive and extract the x32/*.dll in to `steamapps\common\Black Mesa\bin`

Depending on what graphics card you have, it can either increase performance, or decrease it. AMD cards generally operate better on Vulkan than NVidia does. Having these files there will not get you vac banned or anything like that. This repo for dxvk is used in Proton by Valve to play Windows games on Linux by interpreting DirectX calls in to Vulkan ones instead. It just so happens to also work for Windows if you want to run Vulkan instead of native DirectX.

This has also been known to sometimes fix rendering bugs or crashes in other Source Engine mods/games.

**Comment by Ituladan** [comment]
Thanks a lot guys. First of all, the coop mod is amazing and I really appreciate your work here.
The mod and resources running are 1.1.x.
I'll try to run in Vulkan, if I have other news about the issue or some sort of bug log, i'll continue to report here.
Thanks again.   :D

**Comment by Ituladan** [comment]
Update of the situation. I've reintalled my game, not the server, and the problem of game closing was solved. I tested in different situations and its completly stable. 
The problem with flashlight continue, but isn't spoiling our fun.
In my flashlight tests, after my game closing, him take a picture of how was sawing the flashligh on his screen.
![image](https://user-images.githubusercontent.com/105604137/168916662-d4bb409d-ce11-4b07-b0d1-41ac2fa454aa.png)
The flash isn't from hims gun, his light was on the place that i've died. Seems like the game doen't know from who was the light.
I didn't test the editing showed above, yet. I just wanted to report more info about the problem. Thank you all!
