### ISSUE TITLE
Suit and weapon pick-up animations? achivements? ammo carry over between levels? no crowbar start?

### ISSUE THREAD

**Issue by gsergeantGTHB** [ampreeT/SourceCoop#94]
Great mod but feels very lacking compared to just playing the game solo, tried with a friend hoping they'd be able to see all the cool details the game has but we were disappointed when we found out they don't work in this mod. Basically:

- Add suit and weapon first-time pick up animations
- Make ammo carry over between levels, much like how HP does carry over now
- Make players start empty handed / without crowbar

Hope these get added soon

**Comment by Alienmario** [comment]
Hi,
Suit animation will be added in next release.
Weapons and ammo should carry over, just for the first spawn point - not latter checkpoints. This functionality depends on the game being able to resolve valid SteamIDs.
The crowbar is due to a limitation of missing walking animations, you can manually remove it from the *.edt files.
